name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright test
        run: npm run test

      - name: Compare screenshots with Pixelmatch
        run: npm run compare

      - name: Upload visual diffs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff
          path: screenshots/diff/
